package pl.gamefactory.gameOfCard.entities.enums;

public enum Cards {
    /**
     * spades - wino
     * diamond - dzwonek
     * clubs - żołędzie
     * hearts - serce
     */

    CLUBS_1, CLUBS_2, CLUBS_3, CLUBS_4, CLUBS_5, CLUBS_6, CLUBS_7, CLUBS_8, CLUBS_9, CLUBS_10, CLUBS_11, CLUBS_12, CLUBS_13,
    SPADES_1, SPADES_2, SPADES_3, SPADES_4, SPADES_5, SPADES_6, SPADES_7, SPADES_8, SPADES_9, SPADES_10, SPADES_11, SPADES_12, SPADES_13,
    DIAMOND_1, DIAMOND_2, DIAMOND_3, DIAMOND_4, DIAMOND_5, DIAMOND_6, DIAMOND_7, DIAMOND_8, DIAMOND_9, DIAMOND_10, DIAMOND_11, DIAMOND_12, DIAMOND_13,
    HEARTS_1, HEARTS_2, HEARTS_3, HEARTS_4, HEARTS_5, HEARTS_6, HEARTS_7, HEARTS_8, HEARTS_9, HEARTS_10, HEARTS_11, HEARTS_12, HEARTS_13,
}
