spring:
  config:
    activate:
      on-profile: default
  data.mongodb:
    username: rootuser
    password: rootpass
    database: card_db
    port: 27017
    host: localhost
    authentication-database: admin


